### PR TITLE
Allow setting dot-prop values instead of variables

### PR DESCRIPTION
**Pull request by niksy**
This allows to e.g. use `window` properties.

This PR contains adjustments for https://github.com/webpack/imports-loader/pull/21.

### CODE REVIEW

**Comment by SpaceK33z** [comment]
Note that #30 looks a lot like this PR, but has tests.

**Comment by niksy** [comment]
@SpaceK33z huh, you’re right. I was thinking of writing tests, but I’m not familiar with infrastructure used for that in loaders. I guess this PR can be closed and conversation continued in that PR?

**Comment by SpaceK33z** [comment]
Jep. Sorry for the trouble, I hadn't seen that PR earlier. We're all very busy with the webpack v2 release, but I'll put #30 on my todo list to review.

**Comment by SpaceK33z** [comment]
@niksy, might be of interest for you: `imports-loader@0.7.0` was just released with #30.

**Pull request closed without merging**
