### PR TITLE
Support dot notation in variable names

### LINKED ISSUE #22: Is nested import supported ?
for example:

``` javascript
/* foo.js */
module.exports = 1;
```

``` javascript
/* bar.js */
module.exports = foo + 1;
```

``` javascript
/* baz.js */
console.log(bar);
```

i tried:

``` javascript
require('imports?bar=imports?foo!bar!baz'); // webpack error: can't resolve module 'bar'
// or
require('imports?foo,bar!baz'); // runtime error: 'foo' is not defined in bar.js
```

but neither worked.
do i use the wrong syntax or nested import is not supported? (if the latter, maybe i should use loader config or ProvidePlugin.)

### LINKED ISSUE #28: Can't import jquery.ui.position unless aliased
I try to import jquery.ui.position for a another file like so:

```
    module: {
        loaders: [
        {
            test: /index\.js$/,
            loader: 'imports?jquery.ui.position' // This line throws an error
        }
        ]
    },
```

which gets an error much like the following.

> ERROR in ./index.js
> Module parse failed: S:\Github\webpack_import_loader_bug\node_modules\imports-loader\index.js?jquery.ui.position!S:\Github\webpack_import_loader_bug\index.js Unexpected token (2:10)
> You may need an appropriate loader to handle this file type.
> SyntaxError: Unexpected token (2:10)
>     at Parser.pp$4.raise (S:\Github\webpack_import_loader_bug\node_modules\acorn\dist\acorn.js:2221:15)
>     at Parser.pp.unexpected (S:\Github\webpack_import_loader_bug\node_modules\acorn\dist\acorn.js:603:10)
>     at Parser.pp.semicolon (S:\Github\webpack_import_loader_bug\node_modules\acorn\dist\acorn.js:581:61)
>     at Parser.pp$1.parseVarStatement (S:\Github\webpack_import_loader_bug\node_modules\acorn\dist\acorn.js:918:10)
>     at Parser.pp$1.parseStatement (S:\Github\webpack_import_loader_bug\node_modules\acorn\dist\acorn.js:706:19)
>     at Parser.pp$1.parseTopLevel (S:\Github\webpack_import_loader_bug\node_modules\acorn\dist\acorn.js:638:25)
>     at Parser.parse (S:\Github\webpack_import_loader_bug\node_modules\acorn\dist\acorn.js:516:17)
>     at Object.parse (S:\Github\webpack_import_loader_bug\node_modules\acorn\dist\acorn.js:3098:39)
>     at Parser.parse (S:\Github\webpack_import_loader_bug\node_modules\webpack\lib\Parser.js:902:15)
>     at DependenciesBlock.<anonymous> (S:\Github\webpack_import_loader_bug\node_modules\webpack\lib\NormalModule.js:104:16)
>     at DependenciesBlock.onModuleBuild (S:\Github\webpack_import_loader_bug\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
>     at nextLoader (S:\Github\webpack_import_loader_bug\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
>     at S:\Github\webpack_import_loader_bug\node_modules\webpack-core\lib\NormalModuleMixin.js:292:15
>     at runSyncOrAsync (S:\Github\webpack_import_loader_bug\node_modules\webpack-core\lib\NormalModuleMixin.js:160:12)
>     at nextLoader (S:\Github\webpack_import_loader_bug\node_modules\webpack-core\lib\NormalModuleMixin.js:290:3)
>     at S:\Github\webpack_import_loader_bug\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
>     at Storage.finished (S:\Github\webpack_import_loader_bug\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
>     at S:\Github\webpack_import_loader_bug\node_modules\graceful-fs\graceful-fs.js:78:16
>     at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:380:3)

After much hair-pulling and gnashing of teeth I try to alias jquery.ui.position as jquery_ui_position, which works as expected. Apparently the dots within the module name throw the import loader off. 

Am I supposed to escape the dots in some fashion? The documentation doesn't say.

I have set up a tiny example project which demonstrates the issue at https://github.com/sgarcialaguna/import-loader-bug

### LINKED ISSUE #32: injecting variable of submodule
Hi,
I've been stuck over the last few days on injecting jsrsasign into oauth-ng.
Latest test is 
`require('jsrsasign');`
`require('imports?KJUR=jsrsasign,KEYUTIL=jsrsasign!oauth-ng');`

that gives me the following result at the beginning of oauth-ng in the bundle
`var KJUR = __webpack_require__(462);`
`	var KEYUTIL = __webpack_require__(462);`

But what I actually would like to have is something equivalent to 
`var KJUR = __webpack_require__(462).KJUR;`
`	var KEYUTIL = __webpack_require__(462).KEYUTIL;`

Is there anyway to do that? (jsrsasign defines mutiples modules using the exports syntax, and those are the modules I want to inject, not the "container")
Thank you for your help, pulling my haire on this one

### PR DESCRIPTION
**Pull request by fredriks**
import?abc.def.ghi=>1
=> var abc = {};
   abc.def = {};
   abc.def.ghi = 1;

import?window.jQuery=jquery
=> var window = {};
   window.jQuery = require("jquery");

Fixes #28, fixes #22, fixes #32

### CODE REVIEW

**Comment by korya** [comment]
Does this PR handle case of injecting multiple globals? For example: `import?window.jQuery=jquery,window._=lodash`

**Comment by fredriks** [comment]
@korya It does handle multiple globals on window. I've added tests that illustrate various cases.

**Comment by korya** [comment]
Great! Thanks!

**Comment by korya** [comment]
@sokra What do you think? can it be merged?

**Comment by artyomtrityak** [comment]
It looks like this code change may override some variables which are already exist.
For example i have global / local variable `noty`.

```js
import?noty.theme
```

will be compiled to

```js
var noty = {};
var noty.theme = __webpack_require__(XXX);
```

**Comment by SpaceK33z** [comment]
@fredriks, looks like @artyomtrityak is right (disclaimer: I'm looking purely at the code). At the moment you have a specific check for `var window` (`window || {}`), perhaps that could be changed so it works on all variables?

**Comment by fredriks** [comment]
Aye, good point! I'll update the PR with a more general approach.

**Comment by artyomtrityak** [comment]
looks good for me

**Comment by SpaceK33z** [comment]
Thanks a lot @fredriks!

**Comment by SpaceK33z** [comment]
Released `imports-loader@0.7.0` with this, thanks again @fredriks, this has solved a lot of issues.

**Pull request merged**
