### PR TITLE
Add linebreak before postfix

### LINKED ISSUE #5: Add new line before postfix
```
37: var postfix = "\n" + postfixes.join("\n");
```
because if source contain sourcemap comment at the end without new line after, all build is failed with "unexpected end" error

### PR DESCRIPTION
**Pull request by malykhinvi**
Fix #5

### CODE REVIEW

**Comment by Andersos** [comment]
You probably should not check in the `npm-debug.log` file.

**Comment by malykhinvi** [comment]
@Andersos, you are right, thanks.

**Comment by Andersos** [comment]
I think you also only want to change the stuff in the `index.js`file and not the changes to the `README.md` and the `package.json` file.

**Comment by malykhinvi** [comment]
Yes, you are right, but I needed the changes, particularly npm package right away. I could not wait till the pull request will be accepted. I can revert ```index.js``` and ```README.md``` back. Do you have rights to merge this pull request?

**Comment by Andersos** [comment]
Unfortunately I do not. I was looking at this repo and thought I could give some feedback. Looks like the Webpack team is too busy with other stuff.

**Comment by sokra** [comment]
Merged the other PR.

**Comment by Andersos** [comment]
The other PR is https://github.com/webpack/imports-loader/pull/15

**Pull request closed without merging**
